### ISSUE TITLE
Can’t boot

### ISSUE THREAD

**Issue by AnimeJs** [RedFox1293/Bluedot.1#2]
Crashes while initializing, something about a subscribe event if I remember correctly will post a crash report tomorrow most likely when I get home as this was earlier in the day. I already made sure to have the latest version of forge installed as well. Made sure blue dot was the only thing there and it still wouldn’t load

**Comment by RedFox1293** [comment]
Right, so the devs are working on this right now. We are going through the code and working out what the problem is. Expect a new release soon. This is a known issue.

**Comment by AnimeJs** [comment]
Thanks mate
